name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Run PHPCS
      run: php vendor/squizlabs/php_codesniffer/bin/phpcs --standard=psr12 .

    - name: Run PHPMD
      run: vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode
